name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: sudo apt-get install lua5.1
    - run: sudo apt-get install luarocks
    - run: sudo luarocks install luasocket
    - run: npm ci
    - run: npm test
